config/routes.rb
VOSShoppingList::Application.routes.draw do

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :prices

  resources :shoplists do
    resources :products do
      member do
        post :ins
      end
      resources :prices
    end
  end

  resources :products, except: :index do
    resources :prices
  end

  root 'basic_pages#home'
  match '/products', to: 'products#listing', via: 'get'

  match '/signup', to: 'users#new', via: 'get'
  match '/about', to: 'basic_pages#about', via: 'get'
  match '/contact', to: 'basic_pages#contact', via: 'get'
  match '/terms', to: 'basic_pages#terms', via: 'get'
  match '/signin', to: 'sessions#new', via:'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

  match '/shoplists', to: 'shoplists#index', via: 'get'

end

app/models/price.rb
class Price < ActiveRecord::Base
  validates_presence_of :price, :shop
  validates_numericality_of :price, greater_than: 0

  validates :product_id, uniqueness: {scope: [:product_id, :shop]}

  belongs_to :product
end

app/controllers/prices_controller.rb
class PricesController < ApplicationController
  def create
    @product = Product.find(params[:product_id])
    @price = @product.prices.create(price_params)
    redirect_to @product
  end

  def edit
    @cena = Price.find(params[:id])
    @product = Product.find_by_id(@cena.product_id)
  end

  def update
    @price = Price.find(params[:id])
    @product = Product.find_by_id(@price.product_id)

    @price.price = params[:price][:price].gsub(',','.')
    if @price.save
      redirect_to @product
    else
      redirect_to @product
      #TODO add error messages
    end
  end

  private
  def price_params
    params.require(:price).permit(:price, :shop, :until)
  end
end

app/helpers/prices_helper.rb
module PricesHelper
end

app/views/prices/_new_price.html.erb
new price

app/views/prices/_price.html.erb
<li>
  <span class="content">Cena: <%= link_to price.price, edit_price_path(price)%> € - </span>

  <span class="content"><%= price.shop %></span>

  <% unless price.until.nil? %>
    <span class="content"> platí do: <%= price.until %></span>
  <%end%>
</li>

app/views/prices/edit.html.erb
<h1>Upraviť cenu v obchode <%= @cena.shop %></h1>
<h4><%= link_to image_tag("sipkaSpat.png", alt: "Späť"), :back %>  <%= @product.name%></h4>

<%= form_for (@cena) do |f| %>
  <%= f.label :price, 'Nová cena: ' %>
  <%= f.text_field :price %>
  <%= f.submit "Upraviť", class: "btn" %>
<% end %>