config/routes.rb
VOSShoppingList::Application.routes.draw do

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :prices

  resources :shoplists do
    resources :products do
      member do
        post :ins
      end
      resources :prices
    end
  end

  resources :products, except: :index do
    resources :prices
  end

  root 'basic_pages#home'
  match '/products', to: 'products#listing', via: 'get'

  match '/signup', to: 'users#new', via: 'get'
  match '/about', to: 'basic_pages#about', via: 'get'
  match '/contact', to: 'basic_pages#contact', via: 'get'
  match '/terms', to: 'basic_pages#terms', via: 'get'
  match '/signin', to: 'sessions#new', via:'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

  match '/shoplists', to: 'shoplists#index', via: 'get'

end

app/models/product.rb
class Product < ActiveRecord::Base
  validates_presence_of :name
  validates :name, uniqueness: true

  has_many :prices, dependent: :destroy

  has_many :item_in_lists
  has_many :shoplists, through: :item_in_lists

  searchable do
    text :name
    string :category
    string :name
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def new
    @product = Product.new
  end

  def listing
    #TODO fix facets for nil category
    @search = Product.search(include: :prices) do
      fulltext params[:search]
      facet :category, sort: :index
      order_by :name, :asc
      with :category, params[:category] if params[:category].present?
      paginate(page: params[:page], per_page: 35)
    end
    @products = @search.results
    self.new
  end

  def index #vypis vsetkych + pridavanie do shoplistov
    self.listing
    @shoplist = Shoplist.find(params[:shoplist_id])
  end

  def ins
    @shoplist = current_user.shoplists.find(params[:shoplist_id])

    @shoplist.item_in_lists.create(product_id: params[:id], quantity: params[:pocet])
    redirect_to :back
  end

  def show
    @product = Product.find(params[:id])
    @prices = @product.prices.paginate(page: params[:page])
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to :back
    else
      render 'new'
    end
  end

  def destroy
  end

  private
  def product_params
    params.require(:product).permit(:name, :price)
  end
end

app/helpers/products_helper.rb
module ProductsHelper

  def shoplist_add_product(product)
    shoplist = current_user.shoplists[1]
    shoplist.item_in_lists.create(product: product)
  end

end

app/views/products/_facets.html.erb
<style>
  /*bolo by to v tom custom css keby mi to totalne nepokazilo celu stranku...*/
    #menuWrapper {
        left: 0px;
        position: absolute;
        margin-left: 5px;
        margin-top: 50px;
    }
    #menu {
        width: 205px;
        position: absolute;
        top: 0;
        margin-top: 55px;
    }
    #menu.fixed {
        position: fixed;
        top: 0;
    }
</style>

<%= javascript_include_tag 'scrollElement.js' %>

<div id="menuWrapper">
  <div id="menu" class="btn-group-vertical">
    <% @search.facet(:category).rows.each do |row| %>
      <% if params[:category].blank? %>
        <%= link_to params.except(:page).merge({ category: row.value }), class: 'btn btn-default' do %>
          <span class="badge pull-left"><%= row.count %></span>
          <%= row.value%>
        <%end%>
      <% else %>
        <%= link_to  params.except(:category, :page), class: 'btn btn-default' do %>
          <%= image_tag 'sipkaSpat.png', alt: 'Späť' %>
          <%= row.value%>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/products/_new_product.html.erb
<%=form_for(@product) do |f|%>
    <%= f.text_field :name %>
    <%= f.submit "Pridať produkt", class: "btn btn-success" %>
<% end %>

app/views/products/_product.html.erb
<tr>
  <%= form_tag ins_shoplist_product_path(shoplist.id, product.id), method: :post do %>
    <td><input type="number" name="pocet" min="1" step="1" style="width: 50px; height: 28px; margin-top: 7px" value="1"/> ks
    <%= submit_tag 'Pridať', class: 'btn btn-default'%></td>
  <% end %>

  <td><%= link_to product.name, product %></td>

  <% product.prices.each do |price|  %>
    <td><%= price.price %></td>
    <td><%= price.shop %></td>
  <% end %>
</tr>

app/views/products/_searchbox.html.erb
<div class="col-lg-5 pull-right">

  <div class="input-group">
    <%= text_field_tag :search, params[:search], placeholder: 'Hľadať konkrétny produkt', type: :search, class: 'form-control' %>
    <span class="input-group-btn">
      <%= submit_tag 'Hľadať', class: 'btn btn-default', type:'button' %>
    </span>
  </div>
</div>

app/views/products/index.html.erb
<%provide(:title, '| Produkty')%>
<h1>Produkty</h1>



<div >
  <%= form_tag shoplist_products_path, method: :get do %>
      <%= render 'searchbox'%>
  <% end %>
</div>
</br>

<%= render 'facets'%>
</br>

<div><%= will_paginate %></div>

<div>
  <table>
    <tr class="well">
      <th></th>
      <th>Názov produktu</th>
    </tr>
    <%= render partial: "product", collection: @products, locals: { shoplist: @shoplist }%>
  </table>
</div>

<%= will_paginate %>

  <br>
<div><h5 class="pull-right">Vybraný zoznam: <%= link_to @shoplist.name, shoplists_path, class: 'btn btn-default'%></h5></div>


<%= render 'new_product' %>

app/views/products/listing.html.erb
<%provide(:title, '| Zoznam produktov')%>
<h1>Zoznam produktov</h1>

<%# <a href="link" onClick="">nieco</a> %>

<div >
  <%= form_tag products_path, method: :get do %>
      <%= render 'searchbox'%>
  <% end %>
</div>
<br>

<%= render 'facets'%>

<div><%= will_paginate %></div>

<div>
  <table>
    <tr>
      <th>Názov produktu</th>
    </tr>
    <% @products.each do |product|%>
      <tr>
        <td><%= link_to product.name, product %></td>
        <% product.prices.each do |price|  %>
            <td><%= price.price %></td>
            <td><%= price.shop %></td>
        <% end %>
      </tr>
    <%end%>
  </table>
</div>

<%= will_paginate %>

<br>
<%= render 'new_product' %>

app/views/products/new.html.erb
<% provide(:title, '| Pridať produkt') %>
<h1>Pridanie produktu</h1>

<div class="row">
  <div class="span1 offset2">
    <div class="col-md-4">
      <%= render 'new_product' %>
    </div>
  </div>
</div>

app/views/products/show.html.erb
<% provide(:title, "| "+@product.name) %>
<div class="row">

  <h1><%= @product.name%></h1>
  <% if @product.category%>
    <h2>Kategória: <%= @product.category %></h2>
  <%end%>
  <div class="span8">
    <% if @product.prices.any? %>
        <h3>Ceny (<%= @product.prices.count %>)</h3>
         <%= render @prices %>
    <% end %>


    <h4><%= link_to image_tag("sipkaSpat.png", alt: "Späť"), :back %> Pridať novú cenu</h4>
    <%= form_for [@product, Price.new] do |f| %>
        <div class='form-group'>
          <%= f.label :price, 'Cena' %>
          <%= f.text_field :price %>
          <%= f.label :shop, 'Obchod' %>
          <%= f.text_field :shop %>
          <%= f.label :until, 'Platné do (nechať prázdne ak nejde o akciu):' %>
          <%= f.text_field :until %>

        </div>

        <%= f.submit "Pridať cenu", class: "btn btn-success" %>
    <% end %>
  </div>
</div>