config/routes.rb
VOSShoppingList::Application.routes.draw do

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :prices

  resources :shoplists do
    resources :products do
      member do
        post :ins
      end
      resources :prices
    end
  end

  resources :products, except: :index do
    resources :prices
  end

  root 'basic_pages#home'
  match '/products', to: 'products#listing', via: 'get'

  match '/signup', to: 'users#new', via: 'get'
  match '/about', to: 'basic_pages#about', via: 'get'
  match '/contact', to: 'basic_pages#contact', via: 'get'
  match '/terms', to: 'basic_pages#terms', via: 'get'
  match '/signin', to: 'sessions#new', via:'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

  match '/shoplists', to: 'shoplists#index', via: 'get'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    2014 © Lukáš Miškovský
  </small>
  <nav>
    <ul>
      <li><%= link_to " Kontakt", contact_path%></li>
      <li><%= link_to " O projekte", about_path %></li>
      <li><%= link_to " Podmienky", terms_path %></li>
      <li><%= link_to image_tag("print.png", alt: "Vytlačiť"), "javascript:window.print();" %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<style>
    #linkButton {
        margin-top: 10px;
        background:none!important;
        border:none;
        padding:0!important;
        color: gainsboro;
    }
</style>

<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <% if signed_in? %>
        <%= link_to "ShopList", shoplists_path, id: "logo" %>
        <nav>
          <ul class="nav pull-left">
            <li><%= link_to "Produkty", products_path %></li>
            <li><%= link_to "Nákupné zoznamy", shoplists_path %></li>
          </ul>
        </nav>
      <% else %>
        <%= link_to "ShopList", root_path, id: "logo" %>
      <%end%>

      <nav>
        <ul class="nav pull-right">
          <% if signed_in? %>
            <li><%= button_to "Odhlásiť sa", signout_path, method: :delete, id: 'linkButton' %></li>
          <% else %>
            <li><%= link_to "Domov", root_path %></li>
            <li><%= link_to "Prihlásiť sa", signin_path %></li>
          <%end%>
        </ul>
      </nav>
    </div>
  </div>

</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ShopList <%= yield(:title) %></title>

  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>


  <%= csrf_meta_tags %>
  <% render 'layouts/shim'%>
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
  <%= yield %>
  <%= render 'layouts/footer' %>
  <div class="debug_dump">
    <%= debug(params) if Rails.env.development? %>
  </div>
</div>

</body>
</html>